export const FETCH_FINANCIAL_SUMMARY='FETCH_FINANCIAL_SUMMARY';
export const INSERT_INCOME='INSERT_INCOME';
export const INSERT_EXPENSE='INSERT_EXPENSE';
export const USER_SIGNUP='USER_SIGNUP';
export const ALL_EXPENSES='ALL_EXPENSES';
export const ALL_INCOMES='ALL_INCOMES';
export const ALL_TRANSACTIONS='ALL_TRANSACTIONS';